Add
liilkaz/BombApp pull request #2
Opened 2023-08-07 15:21 UTC by dsm5e

Добавил ассеты, MainView и компоненты к нему.

2023-08-07 21:00 UTC, liilkaz commented on Bomb/MainView/Components/ButtonView.swift
> +}
Ошибка: "Use of unknown directive '#Preview'"
Замени на: 
struct ButtonView_Previews: PreviewProvider {
    static var previews: some View {
        ButtonView()
    }
}

2023-08-07 21:01 UTC, liilkaz commented on Bomb/MainView/MainView.swift
> +}
Ошибка: "Use of unknown directive '#Preview'"

Замени на: 
```
struct MainView_Previews: PreviewProvider {
    static var previews: some View {
        MainView()
    }
}
```

2023-08-07 21:02 UTC, liilkaz commented on Bomb/MainView/MainViewSheet.swift
> +}
Ошибка: "Use of unknown directive '#Preview'"

Замени на: 
```
struct MainViewSheet_Previews: PreviewProvider {
    static var previews: some View {
        MainViewSheet()
    }
}
```

2023-08-07 21:02 UTC, liilkaz commented on Bomb/MainView/SettingsView.swift
> +}
Ошибка: "Use of unknown directive '#Preview'"

Замени на: 
```
struct SettingsView_Previews: PreviewProvider {
    static var previews: some View {
        SettingsView()
    }
}
```

2023-08-07 21:11 UTC, liilkaz commented on Bomb/MainView/MainView.swift
> +                }
Ошибка: "Trailing closure passed to parameter of type 'Visibility' that does not accept a closure"

Замени .topBarLeading на .navigationBarLeading
.topBarTrailing на .navigationBarTrailing

2023-08-07 21:14 UTC, liilkaz commented on Bomb/MainView/MainView.swift
> +                    .scaledToFit()
Фоновое изображение сплющивается, надо подумать над настройками

2023-08-07 21:20 UTC, liilkaz commented on Bomb/Assets.xcassets/Background/bgVectorGray.imageset/Topographic 3.png
Лучше заменить 3 png на 1 pdf или svg

2023-08-07 22:08 UTC, ShapovalovIlya commented on Bomb/MainView/MainView.swift
> +                    .scaledToFit()
забыл добавить .ignoreSafeArea() к фону.

2023-08-07 22:11 UTC, ShapovalovIlya commented on Bomb/MainView/MainView.swift
> +                }
Стоит добавить .system(size: 28, weight: .heavy, design: .rounded) в расширение Font для удобства.

2023-08-08 21:37 UTC, liilkaz requested changes
Нужно исправить ошибки

2023-08-08 21:37 UTC, liilkaz commented on Bomb/MainView/View/MainView.swift
> +                            .clipShape(.rect(cornerRadius: 10))
Ошибка: Type 'Shape' has no member 'rect'

2023-08-08 21:37 UTC, liilkaz commented on Bomb/MainView/View/MainView.swift
> +                            .clipShape(.rect(cornerRadius: 10))
Ошибка: Type 'Shape' has no member 'rect'

2023-08-08 21:37 UTC, liilkaz commented on Bomb/MainView/View/MainView.swift
> +                }
Ошибка: Trailing closure passed to parameter of type 'Visibility' that does not accept a closure

2023-08-08 21:37 UTC, liilkaz commented on Bomb/MainView/Components/BackgroundGray.swift
> +//    .ignoresSafeArea()
Закомментированный код нужно удалить

2023-08-08 21:37 UTC, liilkaz commented on Bomb/Assets.xcassets/.DS_Store
.DS_Store удалить. Можно добавить в гитигнор

2023-08-08 21:37 UTC, liilkaz commented on Bomb/Assets.xcassets/Background/.DS_Store
.DS_Store удалить. Можно добавить в гитигнор

2023-08-08 21:37 UTC, liilkaz commented on Bomb/MainView/Components/ButtonView.swift
> +}
Ошибка: "Use of unknown directive '#Preview'"

2023-08-10 16:23 UTC, ShapovalovIlya approved these changes
Bomb/MainView/Extensions/View+Extension.swift - все методы расширений пишутся в тамках одного extension.

2023-08-10 16:32 UTC, liilkaz approved these changes

2023-08-10 16:32 UTC, merged